language: node_js
node_js:
  - "6"
before_install:
  - npm install -g mocha
  - npm install karma-coverage --save-dev
  - npm install -g istanbul
  - npm install -g karma-cli


before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start

after_script:
  - "npm run report"